# Generated by Django 4.2.8 on 2025-12-05 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('agricultor', 'Agricultor'), ('distribuidor', 'Distribuidor'), ('tecnico', 'Técnico'), ('usuario', 'Usuario Regular')], default='usuario', max_length=20, verbose_name='Rol')),
                ('document', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Documento de identidad')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de perfil')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'indexes': [models.Index(fields=['role'], name='core_userpr_role_ce56eb_idx'), models.Index(fields=['is_verified'], name='core_userpr_is_veri_3d0b46_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnidadProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la unidad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('area_hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área en hectáreas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_productivas', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Unidad productiva',
                'verbose_name_plural': 'Unidades productivas',
                'indexes': [models.Index(fields=['owner'], name='core_unidad_owner_i_2dadc9_idx'), models.Index(fields=['is_active'], name='core_unidad_is_acti_1b7cbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('read', 'Leer')], max_length=20, verbose_name='Acción')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo afectado')),
                ('object_id', models.CharField(max_length=100, verbose_name='ID del objeto')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Valores anteriores')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Valores nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx'), models.Index(fields=['model_name', 'action'], name='core_auditl_model_n_1a2a71_idx')],
            },
        ),
    ]
