# Generated by Django 4.2.8 on 2025-12-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('HUMEDAD', 'Humedad'), ('PH', 'pH'), ('TEMPERATURA', 'Temperatura')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensores.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
