# Generated by Django 6.0 on 2025-12-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('unidad_productiva', models.CharField(blank=True, max_length=100, null=True)),
                ('sensores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_agronomicos', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CicloSiembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha_estimada', models.DateField()),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('FINALIZADO', 'Finalizado')], default='EN_PROGRESO', max_length=20)),
                ('superficie_hectareas', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('rendimiento_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='cultivos.cultivo')),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.variedad'),
        ),
    ]
